const products = [
    {
      id: 1,
      name: 'Product 1',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 1',
      category: 'Top Trending',
      Price:'$4,800',
      location:'Chennai',
      date:'16-May',
    },
    {
        id: 2,
      name: 'Product 2',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 1',
      category: 'Top Trending',
      Price:'$800',
      location:'Trichy',
      date:'16-May',
    },
    {
        id: 3,
      name: 'Product 3',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 1',
      category: 'Top Trending',
      Price:'$500',
      location:'Madurai',
      date:'16-May',
    },
    {
        id: 4,
      name: 'Product 4',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 1',
      category: 'Top Trending',
      Price:'$200',
      location:'villupuram',
      date:'16-May',
    },
    {
        id: 5,
      name: 'Product 5',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 1',
      category: 'Top Trending',
      Price:'$300',
      location:'sivakasi',
      date:'16-May',
    },
    {
      id: 6,
      name: 'Product 6',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 2',
      category: 'Recently Added',
      Price:'$50',
      location:'Tiruvallur',
      date:'16-May',
    },
    {
        id: 7,
        name: 'Product 7',
        image: 'https://via.placeholder.com/150',
        description: 'Description of Product 2',
        category: 'Recently Added',
        Price:'$3,900',
        location:'chenai',
        date:'16-May', 
    },
    {
        id:8,
      name: 'Product 8',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 2',
      category: 'Recently Added',
      Price:'$400',
      location:'Chennai',
      date:'16-May',
    },
    {
        id: 9,
      name: 'Product 9',
      image: 'https://via.placeholder.com/150',
      description: 'Description of Product 2',
      category: 'Recently Added',
      Price:'$900',
      location:'rameshwaram',
      date:'16-May',
    },
    {
        id: 10,
        name: 'Product 10',
        image: 'https://via.placeholder.com/150',
        description: 'Description of Product 2',
        category: 'Recently Added',
        Price:'$1000',
        location:'chennai',
        date:'16-May',
    }
    // Add more products as needed
  ];
  
  export default products;
  